### ISSUE TITLE
ReCaptcha does not work if domain is not SSL secure

### ISSUE THREAD

**Issue by nimeshjainjbsols** [Baha2Odeh/yii2-recaptcha-v3#6]
Hi,

Thanks for the extension. It's really simple and easy. 

I have noticed following issue while implementing it:

If I'm not using SSL (as testing is first done on localhost/development server), curl returns `false`.

Can you please set following options?

        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);

If it posses any security risks, can you at least allow setting these parameters in config so that the developer has the freedom to decide whether SSL verification is required or not in curl?

**Comment by Baha2Odeh** [comment]
you can use version 1.2 now ;)
